package SellingApp;
//import com.mysql.cj.jdbc.Driver;

//import com.mysql.cj.jdbc.StatementImpl;
//import com.mysql.cj.protocol.Resultset;
//import com.mysql.cj.xdevapi.Statement;

//import java.sql.Connection;
//import com.mysql.jdbc.*;
//import java.sql.*;
//import java.sql.DriverManager;

import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author raiha
 */
public class DataForm extends javax.swing.JInternalFrame {

    String sql = "SELECT * FROM house";
    public DataForm() {
        initComponents();
        showTable(sql);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabledata = new javax.swing.JTable();
        btnBacktoMenu = new javax.swing.JButton();
        TotalHouseTxt = new javax.swing.JTextField();
        TotalincomeTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CustomerNameTxt = new javax.swing.JTextField();
        AreaTxt = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "order_id", "Customer Name", "Area", "Home Type", "Surface Area", "Price", "Installment Period", "Installment/month"
            }
        ));
        jScrollPane1.setViewportView(tabledata);

        btnBacktoMenu.setText("Back to Menu");
        btnBacktoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacktoMenuActionPerformed(evt);
            }
        });

        TotalHouseTxt.setEditable(false);
        TotalHouseTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalHouseTxtActionPerformed(evt);
            }
        });

        TotalincomeTxt.setEditable(false);

        jLabel1.setText("Number of Homes Sold");

        jLabel2.setText("Total Sales");

        jLabel3.setText("Search Data");

        jLabel4.setText("Customer Name");

        jLabel5.setText("Area");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBacktoMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TotalHouseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(581, 581, 581)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(TotalincomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CustomerNameTxt)
                                    .addComponent(AreaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSearch)
                                    .addComponent(btnDelete))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CustomerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AreaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBacktoMenu)
                    .addComponent(TotalHouseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalincomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBacktoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacktoMenuActionPerformed
        OptionMenu optionmenu = new OptionMenu();
        optionmenu.setVisible(true);
        this.getDesktopPane().add(optionmenu);
        this.dispose();
    }//GEN-LAST:event_btnBacktoMenuActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if(CustomerNameTxt.getText().isEmpty() && AreaTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Insert the desire Data First","error",
                    JOptionPane.ERROR_MESSAGE);
            showTable(sql);
        } else if(CustomerNameTxt.getText().isEmpty()){
            showTable("SELECT * FROM house WHERE area LIKE '%"
            +AreaTxt.getText() + "%'");
        } else if(AreaTxt.getText().isEmpty()){
            showTable("SELECT * FROM house WHERE name LIKE '%"
            +CustomerNameTxt.getText() + "%'");
        } else {
            showTable("SELECT * FROM house WHERE name LIKE '%"
            + CustomerNameTxt.getText() + "%' AND area LIKE '%"
            + AreaTxt.getText() + "%'");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        CustomerNameTxt.setText("");
        AreaTxt.setText("");
        showTable(sql);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void TotalHouseTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalHouseTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalHouseTxtActionPerformed
    public void showTable(String sql){
        try {
            Statement stat = (Statement)ConnectionDb.connectDatabase().createStatement();
            //String sql = "SELECT * FROM house";
            ResultSet rs = stat.executeQuery(sql);
            DefaultTableModel tableModel;
            tableModel = (DefaultTableModel)tabledata.getModel();
            
            tableModel.getDataVector().removeAllElements();
            
            while(rs.next()){
                tableModel.addRow(new Object[] {
                        rs.getString(1), rs.getString(2), rs.getString(3),
                        rs.getString(4), rs.getString(5), rs.getString(6),
                        rs.getString(7), rs.getString(8)
                });  
                long totalIncome = 0;
                int totalHouse = rs.getRow();
                for (int i = 0; i < totalHouse; i++){
                    long income = Long.parseLong((String) tableModel.getValueAt(i, 5));
                    totalIncome += income;
                }
                
                TotalHouseTxt.setText(""+totalHouse);
                TotalincomeTxt.setText(""+totalIncome);
            }
        } catch (SQLException ex){
            Logger.getLogger(DataForm.class.getName()).log(Level.SEVERE, null, ex );
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AreaTxt;
    private javax.swing.JTextField CustomerNameTxt;
    private javax.swing.JTextField TotalHouseTxt;
    private javax.swing.JTextField TotalincomeTxt;
    private javax.swing.JButton btnBacktoMenu;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabledata;
    // End of variables declaration//GEN-END:variables
}
