package SellingApp;

//import com.sun.jdi.connect.spi.Connection;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
//import java.sql.Statement;

/**
 *
 * @author raiha
 */
public class PaymentForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form PaymentForm
     */
    public PaymentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGr = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CustNameTxt = new javax.swing.JTextField();
        PriceLandTxt = new javax.swing.JTextField();
        cmbArea = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbT36 = new javax.swing.JRadioButton();
        rbT45 = new javax.swing.JRadioButton();
        rbT54 = new javax.swing.JRadioButton();
        BuildingPriceTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        OriLandAreaTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AvailableLandTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TotalPriceTxt = new javax.swing.JTextField();
        DPTxt = new javax.swing.JTextField();
        InstallmentPeriodTxt = new javax.swing.JTextField();
        TaxTxt = new javax.swing.JTextField();
        InstallmentTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        AgreementCbx = new javax.swing.JCheckBox();
        btnProcess = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();

        setTitle("Sales Form");

        jLabel1.setText("Customer Name");

        jLabel2.setText("Land Price");

        jLabel3.setText("Area");

        PriceLandTxt.setEditable(false);
        PriceLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        cmbArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- CHOOSE ---", "Bugenvile", "Jasmine", "Flamboyan", " " }));
        cmbArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAreaActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SellingApp/rumah (3).jpg"))); // NOI18N

        jLabel5.setText("Building Price");

        jLabel6.setText("House Type");

        radioButtonGr.add(rbT36);
        rbT36.setText("Type - 36");
        rbT36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbT36ActionPerformed(evt);
            }
        });

        radioButtonGr.add(rbT45);
        rbT45.setText("Type - 45");
        rbT45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbT45ActionPerformed(evt);
            }
        });

        radioButtonGr.add(rbT54);
        rbT54.setText("Type - 54");
        rbT54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbT54ActionPerformed(evt);
            }
        });

        BuildingPriceTxt.setEditable(false);
        BuildingPriceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setText("Original Land Area");

        OriLandAreaTxt.setEditable(false);
        OriLandAreaTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setText("Available Land Area");

        AvailableLandTxt.setEditable(false);
        AvailableLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel9.setText("Price");

        jLabel10.setText("DP");

        jLabel11.setText("Installment Period");

        jLabel12.setText("Tax (10%)");

        jLabel13.setText("Installments / month");

        TotalPriceTxt.setEditable(false);
        TotalPriceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        DPTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        InstallmentPeriodTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        TaxTxt.setEditable(false);
        TaxTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        InstallmentTxt.setEditable(false);
        InstallmentTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel14.setText("Month");

        AgreementCbx.setText("Agree");
        AgreementCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgreementCbxActionPerformed(evt);
            }
        });

        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        TextArea.setColumns(20);
        TextArea.setLineWrap(true);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CustNameTxt)
                            .addComponent(PriceLandTxt)
                            .addComponent(cmbArea, 0, 140, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(rbT36)
                                .addComponent(rbT45)
                                .addComponent(rbT54))
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BuildingPriceTxt)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OriLandAreaTxt)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(AvailableLandTxt)
                            .addComponent(TotalPriceTxt)
                            .addComponent(DPTxt)
                            .addComponent(InstallmentPeriodTxt)
                            .addComponent(TaxTxt)
                            .addComponent(InstallmentTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(AgreementCbx)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CustNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(BuildingPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PriceLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbT36)
                    .addComponent(OriLandAreaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbT45)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbT54)
                            .addComponent(AvailableLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TotalPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(DPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(InstallmentPeriodTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(TaxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(InstallmentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgreementCbx))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProcess)
                            .addComponent(btnSave)
                            .addComponent(btnDelete))
                        .addContainerGap(84, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAreaActionPerformed
        switch(cmbArea.getSelectedIndex()){
            case 0:
                PriceLandTxt.setText("");
                BuildingPriceTxt.setText("");
        radioButtonGr.clearSelection();
        OriLandAreaTxt.setText("");
        AvailableLandTxt.setText("");
        TotalPriceTxt.setText("");
        DPTxt.setText("");
        InstallmentPeriodTxt.setText("");
        InstallmentTxt.setText("");
        TaxTxt.setText("");
        AgreementCbx.setSelected(false);
                break;
                
            case 1:
                PriceLandTxt.setText("500000");
                BuildingPriceTxt.setText("90000000");
        radioButtonGr.clearSelection();
        OriLandAreaTxt.setText("");
        AvailableLandTxt.setText("");
        TotalPriceTxt.setText("");
        DPTxt.setText("");
        InstallmentPeriodTxt.setText("");
        InstallmentTxt.setText("");
        TaxTxt.setText("");
        TextArea.setText("Luxury residential clusters are exclusive residential areas designed to meet the needs and preferences of people with a high lifestyle. These clusters are often equipped with luxurious facilities such as private swimming pools, beautiful gardens, gyms, tennis courts, and sophisticated security systems. They are usually located in prestigious areas and offer houses with attractive architectural designs and high-quality building materials.");
        AgreementCbx.setSelected(false);
                break;
            case 2:
                PriceLandTxt.setText("600000");
                BuildingPriceTxt.setText("120000000");
        radioButtonGr.clearSelection();
        OriLandAreaTxt.setText("");
        AvailableLandTxt.setText("");
        TotalPriceTxt.setText("");
        DPTxt.setText("");
        InstallmentPeriodTxt.setText("");
        InstallmentTxt.setText("");
        TaxTxt.setText("");
        TextArea.setText("Family Housing Clusters: Family housing clusters are residential areas specifically designed to meet the needs of families. They offer homes with a sufficient number of rooms, public facilities such as children's playgrounds, recreation areas, and easy access to educational and health facilities. Family housing clusters usually have safe, comfortable and child-friendly neighborhoods and are often located near commercial areas with easy access to shops, restaurants and shopping centres.");
        AgreementCbx.setSelected(false);
                break;
            default:
                PriceLandTxt.setText("700000");
                BuildingPriceTxt.setText("150000000");
        radioButtonGr.clearSelection();
        OriLandAreaTxt.setText("");
        AvailableLandTxt.setText("");
        TotalPriceTxt.setText("");
        DPTxt.setText("");
        InstallmentPeriodTxt.setText("");
        InstallmentTxt.setText("");
        TaxTxt.setText("");
        TextArea.setText("Family Housing Clusters: Family housing clusters are residential areas specifically designed to meet the needs of families. They offer homes with a sufficient number of rooms, public facilities such as children's playgrounds, recreation areas, and easy access to educational and health facilities. Family housing clusters usually have safe, comfortable and child-friendly neighborhoods and are often located near commercial areas with easy access to shops, restaurants and shopping centers.");
        AgreementCbx.setSelected(false);
                break;
        }
    }//GEN-LAST:event_cmbAreaActionPerformed

    private void rbT36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbT36ActionPerformed
        if(cmbArea.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Pick The area first!");
            radioButtonGr.clearSelection(); 
        } else {
            OriLandAreaTxt.setText("90");
            AvailableLandTxt.setText("54");
            long landPrice = Long.parseLong(PriceLandTxt.getText()),
                    buildingPrice = Long.parseLong(BuildingPriceTxt.getText()),
                    availableLand = Long.parseLong(AvailableLandTxt.getText()),
            totalprice = (availableLand * landPrice) + buildingPrice;
            TotalPriceTxt.setText(""+totalprice);
            
            InstallmentPeriodTxt.setText("");
            DPTxt.setText("");
            TaxTxt.setText("");
            InstallmentTxt.setText("");
        }
    }//GEN-LAST:event_rbT36ActionPerformed

    private void rbT45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbT45ActionPerformed
        if(cmbArea.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Pick The area first!");
            radioButtonGr.clearSelection(); 
        } else {
            OriLandAreaTxt.setText("120");
            AvailableLandTxt.setText("75");
            long landPrice = Long.parseLong(PriceLandTxt.getText()),
                    buildingPrice = Long.parseLong(BuildingPriceTxt.getText()),
                    availableLand = Long.parseLong(AvailableLandTxt.getText()),
            totalprice = (availableLand * landPrice) + buildingPrice;
            TotalPriceTxt.setText(""+totalprice);
            
            InstallmentPeriodTxt.setText("");
            DPTxt.setText("");
            TaxTxt.setText("");
            InstallmentTxt.setText("");
        }
    }//GEN-LAST:event_rbT45ActionPerformed

    private void rbT54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbT54ActionPerformed
        if(cmbArea.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Pick The area first!");
            radioButtonGr.clearSelection(); 
        } else {
            OriLandAreaTxt.setText("140");
            AvailableLandTxt.setText("86");
            long landPrice = Long.parseLong(PriceLandTxt.getText()),
                    buildingPrice = Long.parseLong(BuildingPriceTxt.getText()),
                    availableLand = Long.parseLong(AvailableLandTxt.getText()),
            totalprice = (availableLand * landPrice) + buildingPrice;
            TotalPriceTxt.setText(""+totalprice);
            
            InstallmentPeriodTxt.setText("");
            DPTxt.setText("");
            TaxTxt.setText("");
            InstallmentTxt.setText("");
        }
    }//GEN-LAST:event_rbT54ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        CustNameTxt.setText("");
        PriceLandTxt.setText("");
        BuildingPriceTxt.setText("");
        OriLandAreaTxt.setText("");
        AvailableLandTxt.setText("");
        TotalPriceTxt.setText("");
        DPTxt.setText("");
        InstallmentPeriodTxt.setText("");
        InstallmentTxt.setText("");
        TaxTxt.setText("");
        TextArea.setText("");
        cmbArea.setSelectedIndex(0);
        radioButtonGr.clearSelection();
        AgreementCbx.setSelected(false);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        if(TotalPriceTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Incomplete Selection");
        } else if(DPTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "DP Must be Filled!");
        } else if(InstallmentPeriodTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Fill in the desired installment amount");
        } else{
            long landPrice = Long.parseLong(PriceLandTxt.getText()),
                    buildingPrice = Long.parseLong(BuildingPriceTxt.getText()),
                    availableLand = Long.parseLong(AvailableLandTxt.getText()),
                    dp = Long.parseLong(DPTxt.getText()),
                    installmentPeriod = Long.parseLong(InstallmentPeriodTxt.getText()),
                    totalPrice, Tax, Installment;
            totalPrice = (availableLand * landPrice) + buildingPrice;
            Tax = totalPrice * 10 / 100;
            Installment = (totalPrice + Tax) / installmentPeriod;
            TaxTxt.setText("" + Tax);
            InstallmentTxt.setText("" + Installment);
            
            
        }
    }//GEN-LAST:event_btnProcessActionPerformed

    private void AgreementCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgreementCbxActionPerformed
        if(CustNameTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Customer Name must be filled!");
            AgreementCbx.setSelected(false);
        } else if(TaxTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Press Process Button First!");
            AgreementCbx.setSelected(false);
        } else if(AgreementCbx.isSelected() == true){
            JOptionPane.showMessageDialog(null, "Customer Agree.");
        } else{
            JOptionPane.showMessageDialog(null, "The Order has not been approved");
            AgreementCbx.setSelected(false);
        }
    }//GEN-LAST:event_AgreementCbxActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(AgreementCbx.isSelected() == false){
            JOptionPane.showMessageDialog(null, "Data is still empty, Fill it first!","error",JOptionPane.ERROR_MESSAGE);
        } else{
            String typeHouse;
            if (rbT36.isSelected()){
                typeHouse = "Type 36";
            } else if (rbT45.isSelected()){
                typeHouse = "Type 45";
            } else {
                typeHouse = "Type 54";
            }
            
            try {
                String sql = "INSERT INTO house (name, area, type, wide, price, installmentAmount, InstallmentPeriiod) VALUES('"
                        + CustNameTxt.getText() + "','"
                        + cmbArea.getSelectedItem() + "','"
                        + typeHouse + "','"
                        + OriLandAreaTxt.getText() + "','"
                        + TotalPriceTxt.getText() + "','"
                        + InstallmentPeriodTxt.getText() + "','"
                        + InstallmentTxt.getText() + "')";
                Connection conn = (Connection)ConnectionDb.connectDatabase();
                PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
                pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            OptionMenu optionMenu = new OptionMenu();
            optionMenu.setVisible(true);
            this.getDesktopPane().add(optionMenu);
            this.dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AgreementCbx;
    private javax.swing.JTextField AvailableLandTxt;
    private javax.swing.JTextField BuildingPriceTxt;
    private javax.swing.JTextField CustNameTxt;
    private javax.swing.JTextField DPTxt;
    private javax.swing.JTextField InstallmentPeriodTxt;
    private javax.swing.JTextField InstallmentTxt;
    private javax.swing.JTextField OriLandAreaTxt;
    private javax.swing.JTextField PriceLandTxt;
    private javax.swing.JTextField TaxTxt;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JTextField TotalPriceTxt;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup radioButtonGr;
    private javax.swing.JRadioButton rbT36;
    private javax.swing.JRadioButton rbT45;
    private javax.swing.JRadioButton rbT54;
    // End of variables declaration//GEN-END:variables
}
